# Generated by Django 4.2.3 on 2023-07-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_online_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='onlineshop',
            table='advertisements',
        ),
    ]
