# Generated by Django 4.2.3 on 2023-08-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_online_shop', '0002_alter_onlineshop_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlineshop',
            old_name='update_time',
            new_name='updated_time',
        ),
        migrations.AlterField(
            model_name='onlineshop',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
