# Generated by Django 4.2.3 on 2023-08-07 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_online_shop', '0003_rename_update_time_onlineshop_updated_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineshop',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
            preserve_default=False,
        ),
    ]
